create table if not exists public.events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  symbol text,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists events_event_type_idx on public.events (event_type);
create index if not exists events_symbol_created_at_idx on public.events (upper(symbol), created_at);
create index if not exists events_created_at_idx on public.events (created_at desc);

alter table public.events enable row level security;

create table if not exists public.simulation_summaries (
  simulation_run_id text primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists simulation_summaries_created_at_idx on public.simulation_summaries (created_at desc);

alter table public.simulation_summaries enable row level security;

create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  provider text not null,
  event_type text not null,
  severity text not null,
  message text not null,
  delivery_status text not null,
  error_message text
);

create index if not exists notification_events_timestamp_idx on public.notification_events (timestamp desc);
create index if not exists notification_events_provider_idx on public.notification_events (provider);

alter table public.notification_events enable row level security;
